### ISSUE TITLE
Tracker integration

### ISSUE THREAD

**Issue by Amatrelan** [Amatrelan/raindl#2]
There is a many different trackers

## Trackers to implement
- [ ] [notify.moe](notify.moe)
- [ ] [myanimelist](myanimelist.net) will be pain in the ass, they don't have documentation at all?
- [ ] Some local tracker?
- [ ] Create own tracker?
